spring:
  datasource:
    url: jdbc:mysql://106.52.14.44:3306/onlinejudge?useSSL=false&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: OnlineJudge
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  activemq:
    broker-url: tcp://106.52.14.44:61616
    user: publisher
    password: OJDEV
    pool:
      enabled: true
      max-connections: 100
  jms:
    pub-sub-domain: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

server:
  port: 8090

file:
  upload:
    path:
      test-case: G:\Desktop\upload
      file-name-max-length: 100
  test-case:
    path: G:\Desktop\testCases
    temp-path: G:\Desktop\testTempCases
  code:
    path: G:\Desktop\codesss